global using TimeZoneConverter;
global using csharp_webhook_based_jobscheduler.API.Configurations;
global using csharp_webhook_based_jobscheduler.API.Services.HttpClientServices;
global using FluentValidation;
global using Hangfire;
global using Newtonsoft.Json;
global using Microsoft.AspNetCore.Mvc;
global using csharp_webhook_based_jobscheduler.API.Features.Core;
global using csharp_webhook_based_jobscheduler.API.Features.JobScheduler.CreateJob;
global using MediatR;
global using csharp_webhook_based_jobscheduler.API.Enums;
global using csharp_webhook_based_jobscheduler.API.Utils;
global using csharp_webhook_based_jobscheduler.API.Extensions;
global using csharp_webhook_based_jobscheduler.API.Models;
global using System.Text;
global using static System.Net.Mime.MediaTypeNames;
global using System.Net;
